permalink: /:categories/:year/:month/:day/:title
paginate: 2
paginate_path: '/page-:num/'
author: Alexander Cederblad
timezone: UTC
collections:
  - projects
plugins:
  - 'jekyll-feed'
  - 'jekyll-paginate'
